#!/usr/bin/env node

// @note -----
// Please understand, this code was created by an amature. My team mates are much
// better coders than me, but their skills were needed elsewhere. If you find errors,
// feel free to let me know so that I can improve! -@d0vr